### ISSUE TITLE
/bin/sh: 1: ./mvnw: Permission denied

### ISSUE THREAD

**Issue by solairerove** [meeteor-13/core#5]
Step 5/13 : RUN ./mvnw -Dmaven.test.skip=true install
 ---> Running in aab4f751b16d
/bin/sh: 1: ./mvnw: Permission denied
ERROR: Service 'core' failed to build: The command '/bin/sh -c ./mvnw -Dmaven.test.skip=true install' returned a non-zero code: 126

**Comment by alebabai** [comment]
Fixed, thanks.
